// <auto-generated />
using System;
using Hekki.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hekki.Infrastructure.Migrations
{
    [DbContext(typeof(HekkiDbContext))]
    [Migration("20260527183652_UpdateArchitecture")]
    partial class UpdateArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RegulationId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("RegulationId");

                    b.ToTable("heats", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatEntryEntity", b =>
                {
                    b.Property<int>("HeatId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int?>("GridPosition")
                        .HasColumnType("integer");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("KartNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeedOrder")
                        .HasColumnType("integer");

                    b.HasKey("HeatId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("heat_entries", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatResultEntity", b =>
                {
                    b.Property<int>("HeatId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<long?>("BestLapMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int?>("Laps")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TotalTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("HeatId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("heat_results", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.PilotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("pilots", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RegulationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegulationId");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.HasIndex("RaceId", "PilotId")
                        .IsUnique();

                    b.ToTable("race_participants", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RegulationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("regulations", (string)null);
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatEntity", b =>
                {
                    b.HasOne("Hekki.Infrastructure.Entities.RaceEntity", "RaceEntity")
                        .WithMany("Heats")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hekki.Infrastructure.Entities.RegulationEntity", "RegulationEntity")
                        .WithMany()
                        .HasForeignKey("RegulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaceEntity");

                    b.Navigation("RegulationEntity");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatEntryEntity", b =>
                {
                    b.HasOne("Hekki.Infrastructure.Entities.HeatEntity", "Heat")
                        .WithMany("HeatEntries")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hekki.Infrastructure.Entities.RaceParticipantEntity", "Participant")
                        .WithMany("HeatEntries")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heat");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatResultEntity", b =>
                {
                    b.HasOne("Hekki.Infrastructure.Entities.HeatEntity", "Heat")
                        .WithMany("HeatParticipantResults")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hekki.Infrastructure.Entities.RaceParticipantEntity", "Participant")
                        .WithMany("HeatResults")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heat");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceEntity", b =>
                {
                    b.HasOne("Hekki.Infrastructure.Entities.RegulationEntity", "Regulation")
                        .WithMany()
                        .HasForeignKey("RegulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceParticipantEntity", b =>
                {
                    b.HasOne("Hekki.Infrastructure.Entities.PilotEntity", "Pilot")
                        .WithMany("Participations")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hekki.Infrastructure.Entities.RaceEntity", "Race")
                        .WithMany("Participants")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilot");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.HeatEntity", b =>
                {
                    b.Navigation("HeatEntries");

                    b.Navigation("HeatParticipantResults");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.PilotEntity", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceEntity", b =>
                {
                    b.Navigation("Heats");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Hekki.Infrastructure.Entities.RaceParticipantEntity", b =>
                {
                    b.Navigation("HeatEntries");

                    b.Navigation("HeatResults");
                });
#pragma warning restore 612, 618
        }
    }
}
